name: Tłusty Temat
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12318
title: Tłusty Temat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffa800'
    - '#ff6c00'
    - '#df0000'
    - '#4e0000'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
