name: Tłusty Temat
favicon: null
layout_spectrum: 0.9014469529502094
typography_spectrum: 0.1771104745566845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5190413619857281
  lightness: 0.11833487101830542
  saturation: 0.6671211004722863
  rhythmicContrast: 0.10262311180122197
purpose: []
